### ISSUE TITLE
Channel name validation against default KeyStringAttribute excludes valid names

### ISSUE THREAD

**Issue by JMolenkamp** [atc-net/atc-kepware#31]
The channel name validation against the default `KeyStringAttribute` excludes valid names (using KEPServerEX v6.11.764.0), which makes it impossible to get the devices for a channel that for instance contains a space.

https://github.com/atc-net/atc-kepware/blob/c7af84a0057a8586a78f9737847c7b175370cde6/src/Atc.Kepware.Configuration/Services/Connectivity/KepwareConfigurationClientConnectivity.cs#L763-L774

The default `KeyStringAttribute` excludes all use of the `InvalidCharacters` and does not allow for starting with an `InvalidPrefixStrings`:

``` csharp
public KeyStringAttribute()
{
    Required = true;
    InvalidCharacters = new[] { ' ', '.', '@', '\'' };
    InvalidPrefixStrings = new[] { "_" };
    RegularExpression = string.Empty;
}
```

However, all `InvalidCharacters` except for the period are allowed in the channel name:

![image](https://github.com/atc-net/atc-kepware/assets/59445808/746df87b-4e92-4474-b9fa-3442a619914b)

The restrictions for the channel name are described in the error message below, although the @ character actually is allowed (as seen above):

![image](https://github.com/atc-net/atc-kepware/assets/59445808/2e11b564-6d04-4f7c-9b07-515df7727961)

**Comment by perkops** [comment]
New release ready: https://www.nuget.org/packages/Atc.Kepware.Configuration/1.1.18

Thanks again for the contribution.
